export const shapes = {
    "spiral": [
        "size = 600;",
        "",
        "func shape(c, s) {",
        "  i = 0;",
        "",
        "  while (i < c * s) {",
        "    forward (size / c);",
        "    right (360 / c);",
        "    i = i + 1;",
        "  }",
        "}",
        "",
        "left 30;",
        "forward size * 0.5;",
        "x = 41;",
        "",
        "while (x > 0) {",
        "  shape(55, 0.5);",
        "  right 90;",
        "  shape(55, 0.5);",
        "  x = x - 1;",
        "}",
    ],
    "koch": [
        "func min(a, b) {",
        "  if a < b {",
        "    return a;",
        "  }",
        "",
        "  return b;",
        "}",
        "",
        "func segment(n, length) {",
        "  if n == 0 {",
        "    forward length;",
        "    return;",
        "  }",
        "",
        "  l = (length / 3);",
        "",
        "  segment(n - 1, l);",
        "  left 60;",
        "  segment(n - 1, l);",
        "  right 120;",
        "  segment(n - 1, l);",
        "  left 60;",
        "  segment(n - 1, l);",
        "}",
        "",
        "func triangle(n, length) {",
        "  left 60;",
        "  segment(n, length);",
        "  right 120;",
        "  segment(n, length);",
        "  right 120;",
        "  segment(n, length);",
        "  left 180;",
        "}",
        "",
        "i = min(3, 5);",
        "",
        "while i < 6 {",
        "  triangle(i, 400);",
        "  i = i + 1;",
        "}",
        ""
    ],
    "emoji_test": [
        "cow🤠boy = 200;",
        "forward cow🤠boy;",
        "right 90;",
        "forward cow🤠boy;",
        "right 90;",
        "forward cow🤠boy;",
        "right 90;",
        "forward cow🤠boy;",
    ]
}